// This file is @generated by prost-build.
/// Common types
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BoundingBox {
    #[prost(float, tag = "1")]
    pub x1: f32,
    #[prost(float, tag = "2")]
    pub y1: f32,
    #[prost(float, tag = "3")]
    pub x2: f32,
    #[prost(float, tag = "4")]
    pub y2: f32,
    #[prost(float, tag = "5")]
    pub confidence: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Landmark {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FaceDetection {
    #[prost(message, optional, tag = "1")]
    pub bbox: ::core::option::Option<BoundingBox>,
    /// 5 keypoints
    #[prost(message, repeated, tag = "2")]
    pub landmarks: ::prost::alloc::vec::Vec<Landmark>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FaceAttributes {
    #[prost(int32, tag = "1")]
    pub age: i32,
    /// "male" | "female"
    #[prost(string, tag = "2")]
    pub gender: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub gender_confidence: f32,
    /// "neutral" | "happy" | "sad" | "angry" | "fear" | "disgust" | "surprise"
    #[prost(string, tag = "4")]
    pub emotion: ::prost::alloc::string::String,
    #[prost(float, tag = "5")]
    pub emotion_confidence: f32,
}
/// Detect
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectRequest {
    /// Raw image bytes (JPEG/PNG)
    #[prost(bytes = "vec", tag = "1")]
    pub image_data: ::prost::alloc::vec::Vec<u8>,
    /// Default: 0.5
    #[prost(float, tag = "2")]
    pub confidence_threshold: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectResponse {
    #[prost(message, repeated, tag = "1")]
    pub faces: ::prost::alloc::vec::Vec<FaceDetection>,
    #[prost(int32, tag = "2")]
    pub inference_time_ms: i32,
}
/// Register
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub image_data: ::prost::alloc::vec::Vec<u8>,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub person_id: ::prost::alloc::string::String,
    /// Display name
    #[prost(string, tag = "3")]
    pub person_name: ::prost::alloc::string::String,
    /// Optional metadata
    #[prost(map = "string, string", tag = "4")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// UUID of the registered face
    #[prost(string, tag = "2")]
    pub face_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Compare (1:1)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompareRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub image1_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub image2_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CompareResponse {
    /// 0.0 - 1.0
    #[prost(float, tag = "1")]
    pub similarity: f32,
    /// Based on threshold
    #[prost(bool, tag = "2")]
    pub is_same_person: bool,
    #[prost(int32, tag = "3")]
    pub inference_time_ms: i32,
}
/// Identify (1:N)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdentifyRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub image_data: ::prost::alloc::vec::Vec<u8>,
    /// Max results, default: 5
    #[prost(int32, tag = "2")]
    pub top_k: i32,
    /// Min similarity, default: 0.5
    #[prost(float, tag = "3")]
    pub threshold: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdentifyResult {
    #[prost(string, tag = "1")]
    pub person_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub person_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub face_id: ::prost::alloc::string::String,
    #[prost(float, tag = "4")]
    pub similarity: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdentifyResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<IdentifyResult>,
    #[prost(int32, tag = "2")]
    pub inference_time_ms: i32,
}
/// Analyze
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnalyzeRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub image_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnalyzeResponse {
    #[prost(message, repeated, tag = "1")]
    pub faces: ::prost::alloc::vec::Vec<FaceAnalysis>,
    #[prost(int32, tag = "2")]
    pub inference_time_ms: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FaceAnalysis {
    #[prost(message, optional, tag = "1")]
    pub bbox: ::core::option::Option<BoundingBox>,
    #[prost(message, optional, tag = "2")]
    pub attributes: ::core::option::Option<FaceAttributes>,
}
/// Delete
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteRequest {
    /// UUID of the face to delete
    #[prost(string, tag = "1")]
    pub face_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Health
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// detector, embedder, etc.
    #[prost(map = "string, bool", tag = "3")]
    pub models_loaded: ::std::collections::HashMap<::prost::alloc::string::String, bool>,
}
/// Generated server implementations.
pub mod face_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with FaceServiceServer.
    #[async_trait]
    pub trait FaceService: std::marker::Send + std::marker::Sync + 'static {
        /// Detect faces in an image
        async fn detect(
            &self,
            request: tonic::Request<super::DetectRequest>,
        ) -> std::result::Result<tonic::Response<super::DetectResponse>, tonic::Status>;
        /// Register a face to the database
        async fn register(
            &self,
            request: tonic::Request<super::RegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterResponse>,
            tonic::Status,
        >;
        /// Compare two faces (1:1 verification)
        async fn compare(
            &self,
            request: tonic::Request<super::CompareRequest>,
        ) -> std::result::Result<tonic::Response<super::CompareResponse>, tonic::Status>;
        /// Identify a face from the database (1:N search)
        async fn identify(
            &self,
            request: tonic::Request<super::IdentifyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IdentifyResponse>,
            tonic::Status,
        >;
        /// Analyze face attributes (age, gender, emotion)
        async fn analyze(
            &self,
            request: tonic::Request<super::AnalyzeRequest>,
        ) -> std::result::Result<tonic::Response<super::AnalyzeResponse>, tonic::Status>;
        /// Delete a registered face
        async fn delete(
            &self,
            request: tonic::Request<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status>;
        /// Health check
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
    }
    /// Face Recognition Service
    #[derive(Debug)]
    pub struct FaceServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> FaceServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for FaceServiceServer<T>
    where
        T: FaceService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/face.FaceService/Detect" => {
                    #[allow(non_camel_case_types)]
                    struct DetectSvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::DetectRequest>
                    for DetectSvc<T> {
                        type Response = super::DetectResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DetectRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::detect(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DetectSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/face.FaceService/Register" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterSvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::RegisterRequest>
                    for RegisterSvc<T> {
                        type Response = super::RegisterResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::register(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/face.FaceService/Compare" => {
                    #[allow(non_camel_case_types)]
                    struct CompareSvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::CompareRequest>
                    for CompareSvc<T> {
                        type Response = super::CompareResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CompareRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::compare(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CompareSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/face.FaceService/Identify" => {
                    #[allow(non_camel_case_types)]
                    struct IdentifySvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::IdentifyRequest>
                    for IdentifySvc<T> {
                        type Response = super::IdentifyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IdentifyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::identify(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IdentifySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/face.FaceService/Analyze" => {
                    #[allow(non_camel_case_types)]
                    struct AnalyzeSvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::AnalyzeRequest>
                    for AnalyzeSvc<T> {
                        type Response = super::AnalyzeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AnalyzeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::analyze(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AnalyzeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/face.FaceService/Delete" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::DeleteRequest>
                    for DeleteSvc<T> {
                        type Response = super::DeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::delete(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/face.FaceService/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: FaceService>(pub Arc<T>);
                    impl<
                        T: FaceService,
                    > tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FaceService>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for FaceServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "face.FaceService";
    impl<T> tonic::server::NamedService for FaceServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
